package com.portal.android.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBDEFB)
val md_theme_light_onPrimaryContainer = Color(0xFF0D47A1)
val md_theme_light_secondary = Color(0xFF26A69A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB2DFDB)
val md_theme_light_onSecondaryContainer = Color(0xFF004D40)
val md_theme_light_tertiary = Color(0xFFFF9800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF5F5F5)
val md_theme_light_onBackground = Color(0xFF212121)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF212121)
val md_theme_light_error = Color(0xFFB00020)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_outline = Color(0xFF757575)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF90CAF9)
val md_theme_dark_onPrimary = Color(0xFF0D47A1)
val md_theme_dark_primaryContainer = Color(0xFF1565C0)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBDEFB)
val md_theme_dark_secondary = Color(0xFF80CBC4)
val md_theme_dark_onSecondary = Color(0xFF004D40)
val md_theme_dark_secondaryContainer = Color(0xFF00695C)
val md_theme_dark_onSecondaryContainer = Color(0xFFB2DFDB)
val md_theme_dark_tertiary = Color(0xFFFFB74D)
val md_theme_dark_onTertiary = Color(0xFFE65100)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE0E0E0)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE0E0E0)
val md_theme_dark_error = Color(0xFFCF6679)
val md_theme_dark_onError = Color(0xFF000000)
val md_theme_dark_outline = Color(0xFF9E9E9E)
