/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated/notices'
import { Route as AuthenticatedMyStudentsRouteImport } from './routes/_authenticated/my-students'
import { Route as AuthenticatedMyPayslipsRouteImport } from './routes/_authenticated/my-payslips'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsAddStudentRouteImport } from './routes/_authenticated/students/add-student'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students/$studentId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyStudentsRoute = AuthenticatedMyStudentsRouteImport.update({
  id: '/my-students',
  path: '/my-students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyPayslipsRoute = AuthenticatedMyPayslipsRouteImport.update({
  id: '/my-payslips',
  path: '/my-payslips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsAddStudentRoute =
  AuthenticatedStudentsAddStudentRouteImport.update({
    id: '/students/add-student',
    path: '/students/add-student',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/my-payslips': typeof AuthenticatedMyPayslipsRoute
  '/my-students': typeof AuthenticatedMyStudentsRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/add-student': typeof AuthenticatedStudentsAddStudentRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/my-payslips': typeof AuthenticatedMyPayslipsRoute
  '/my-students': typeof AuthenticatedMyStudentsRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/add-student': typeof AuthenticatedStudentsAddStudentRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/my-payslips': typeof AuthenticatedMyPayslipsRoute
  '/_authenticated/my-students': typeof AuthenticatedMyStudentsRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/students/add-student': typeof AuthenticatedStudentsAddStudentRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/welcome'
    | '/admissions'
    | '/assignments'
    | '/attendance'
    | '/fees'
    | '/leave'
    | '/my-payslips'
    | '/my-students'
    | '/notices'
    | '/payroll'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/students/$studentId'
    | '/students/add-student'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/welcome'
    | '/admissions'
    | '/assignments'
    | '/attendance'
    | '/fees'
    | '/leave'
    | '/my-payslips'
    | '/my-students'
    | '/notices'
    | '/payroll'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/users'
    | '/'
    | '/students/$studentId'
    | '/students/add-student'
    | '/students'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/welcome'
    | '/_authenticated/admissions'
    | '/_authenticated/assignments'
    | '/_authenticated/attendance'
    | '/_authenticated/fees'
    | '/_authenticated/leave'
    | '/_authenticated/my-payslips'
    | '/_authenticated/my-students'
    | '/_authenticated/notices'
    | '/_authenticated/payroll'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students/add-student'
    | '/_authenticated/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-students': {
      id: '/_authenticated/my-students'
      path: '/my-students'
      fullPath: '/my-students'
      preLoaderRoute: typeof AuthenticatedMyStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-payslips': {
      id: '/_authenticated/my-payslips'
      path: '/my-payslips'
      fullPath: '/my-payslips'
      preLoaderRoute: typeof AuthenticatedMyPayslipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/add-student': {
      id: '/_authenticated/students/add-student'
      path: '/students/add-student'
      fullPath: '/students/add-student'
      preLoaderRoute: typeof AuthenticatedStudentsAddStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedMyPayslipsRoute: typeof AuthenticatedMyPayslipsRoute
  AuthenticatedMyStudentsRoute: typeof AuthenticatedMyStudentsRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedStudentsAddStudentRoute: typeof AuthenticatedStudentsAddStudentRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedMyPayslipsRoute: AuthenticatedMyPayslipsRoute,
  AuthenticatedMyStudentsRoute: AuthenticatedMyStudentsRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedStudentsAddStudentRoute: AuthenticatedStudentsAddStudentRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
